# Generated by Django 4.2 on 2025-01-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('NotStarted', 'NotStarted')], max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
